### PR TITLE
fix(onnxparser)!: Make sure the parser can't be dropped before build

### LINKED ISSUE #71: Need to make sure with lifetimes/other API that OnnxParser
Probably best to consume the network and then access it via a getter, so that who ever uses the parser can only do things with the network while the parser is still alive.

The semantics of `converters::trtx::TrtxConverter::build_network` were good as it only allowed safe use.

### PR DESCRIPTION
**Pull request by theHamsta**
Before one could do

```rs
    let mut network = builder.create_network(0)?;
    if do_parse {
	  debug!("Processing as ONNX file: {onnx_path:?}");
	  let mut parser = OnnxParser::new(&mut network, &logger)?;
	  parser.parse_from_file(&onnx_path.to_string_lossy().clone(), 5)?;
	  // parser dropped here
    }

    // build uses weights from dropped parser
    let serialized = builder
	  .build_serialized_network(&mut network, &mut config)
	  .with_context(|| format!("Fail to build {onnx_path:?}"))?;

    // parser creation needs to be hoisted from if to have it still alive
    // during build
```

uses #70 (where I saw this mistake)

Suggestion is to do
```rs
  let mut network = builder.create_network(0)?;
  let mut parser = OnnxParser::new(network, &logger)?;
  // network consumed by parser. Can't use network anymore without living parser

  // access to network only via getter, ensures living parser
  let serialized = builder
    .build_serialized_network(parser.network_mut(), &mut config)
    .with_context(|| format!("Fail to build {onnx_path:?}"))?;
```

Fixes https://github.com/rustnn/trtx-rs/issues/71

### CODE REVIEW

File: trtx/src/onnx_parser.rs [hunk 1]
```diff
@@ -16,10 +15,10 @@ use crate::network::NetworkDefinition;
 /// [`trtx_sys::nvonnxparser::IParser`] — C++ [`nvonnxparser::IParser`](https://docs.nvidia.com/deeplearning/tensorrt-rtx/latest/_static/cpp-api/classnvonnxparser_1_1_i_parser.html).
 pub struct OnnxParser<'network> {
     inner: UniquePtr<nvonnxparser::IParser>,
-    _network: PhantomData<&'network nvinfer1::INetworkDefinition>,
+    network: NetworkDefinition<'network>,
```
Comment (theHamsta) [inline trtx/src/onnx_parser.rs:18]: now there is a network and parser. Now, the can only be used while both are alive.

 But when we finished using. is there a need that one gets destroyed before the other? TODO: check

**Review by mtavenrath — APPROVED** [review]
